### ISSUE TITLE
Трата очков

### ISSUE THREAD

**Issue by InfernumPegasus** [Vladislavlatfulin/amogus#1]
Добрый день! Есть ли магазин, в котором можно потратить набранные после мини-игры очки?

**Comment by Vladislavlatfulin** [comment]
Добрый день! В данный момент временем трата очков в магазине находится в разработке. В ближайших обновлениях игры будет добавлена эта функция. Следите за обновлениями на нашем сайте.

**Comment by InfernumPegasus** [comment]
Добрый день! 🤝

**Comment by Vladislavlatfulin** [comment]
Добрый день!🤝
