### ISSUE TITLE
Оптимизация внедрения зависимостей

### ISSUE THREAD

**Issue by InfernumPegasus** [Vladislavlatfulin/amogus#3]
Здравствуйте! При внедрении зависимостей каждое внедрение лучше выносить в отдельный метод.

**Comment by Vladislavlatfulin** [comment]
Здравствуйте! Будет исправлено в ближайшее время.

**Comment by InfernumPegasus** [comment]
Здравствуйте! Ок.

**Comment by Vladislavlatfulin** [comment]
Здравствуйте! Ок.
