### ISSUE TITLE
Удаление неиспользованных библиотек и методов

### ISSUE THREAD

**Issue by InfernumPegasus** [Vladislavlatfulin/amogus#4]
Доброго времени суток! Неиспользуемые библиотеки лучше удалять в скриптах, это повысит качество и скорость кода. Также следует избегать вызовов методов FindObjectOfType и FindWithTag класса GameObject.

**Comment by Vladislavlatfulin** [comment]
Доброго времени суток! В ближайшее время эти вызовы(FindObjectOfType и FindWithTag) будут заменены с помощью Di-Container. В данный момент используется как временное решение.  неиспользуемые библиотеки будут также удалены.

**Comment by InfernumPegasus** [comment]
Доброго времени суток! Ок.

**Comment by Vladislavlatfulin** [comment]
Доброго времени суток! Ок.
